In [1]:
import pandas as pd
import numpy as np

In [4]:
# Load Training data
df = pd.read_csv('data/clean/Training.csv')

df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [5]:
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [6]:
X = df.iloc[:, :-1]
y = df['prognosis']


In [7]:
len(df.columns)


133

In [8]:
cols = df.columns

In [9]:
cols = cols[:-1]

In [10]:
cols

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'pus_filled_pimples', 'blackheads', 'scurring', 'skin_peeling',
       'silver_like_dusting', 'small_dents_in_nails', 'inflammatory_nails',
       'blister', 'red_sore_around_nose', 'yellow_crust_ooze'],
      dtype='object', length=132)

In [11]:
len(df['prognosis'].unique())

41

## 41 different type of target diseases are available in the manual training dataset.

In [12]:
df.__getstate__()

{'_mgr': BlockManager
 Items: Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
        'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
        'ulcers_on_tongue',
        ...
        'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
        'small_dents_in_nails', 'inflammatory_nails', 'blister',
        'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
       dtype='object', length=133)
 Axis 1: RangeIndex(start=0, stop=4920, step=1)
 IntBlock: slice(0, 132, 1), 132 x 4920, dtype: int64
 ObjectBlock: slice(132, 133, 1), 1 x 4920, dtype: object,
 '_typ': 'dataframe',
 '_metadata': [],
 'attrs': {}}

In [13]:
# Train, Test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=20)

In [31]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier()

In [32]:
rf_clf.fit(X_train, y_train)

print("Accuracy on split test: ", rf_clf.score(X_test,y_test))

Accuracy on split test:  1.0


In [33]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

importances = rf_clf.feature_importances_
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

Feature ranking:


In [34]:
features = cols

In [35]:
for f in range(10):
    print("%d. feature %d - %s (%f)" % (f + 1, indices[f], features[indices[f]] ,importances[indices[f]]))


1. feature 97 - muscle_pain (0.021108)
2. feature 56 - chest_pain (0.017009)
3. feature 109 - lack_of_concentration (0.016588)
4. feature 33 - dark_urine (0.016193)
5. feature 11 - vomiting (0.015793)
6. feature 41 - mild_fever (0.015731)
7. feature 7 - stomach_pain (0.015422)
8. feature 43 - yellowing_of_eyes (0.015338)
9. feature 14 - fatigue (0.015294)
10. feature 0 - itching (0.015229)


In [19]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [20]:
print ("DecisionTree")
dt = DecisionTreeClassifier()
clf_dt=dt.fit(X_train,y_train)
print ("Acurracy: ", clf_dt.score(X_test,y_test))

DecisionTree
Acurracy:  1.0


In [36]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.naive_bayes import MultinomialNB

In [37]:
mnb = MultinomialNB()
mnb = mnb.fit(X_train, y_train)

In [38]:
mnb.score(X_test, y_test)

1.0

In [39]:
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score
print ("cross result========")
scores = cross_val_score(mnb, X_test, y_test, cv=3)
print (scores)
print (scores.mean())

cross result========
[1. 1. 1.]
1.0


In [40]:
print ("cross result========")
scores = cross_val_score(dt, X_test, y_test, cv=3)
print (scores)
print (scores.mean())

cross result========
[0.97357724 0.98170732 0.95528455]
0.970189701897019


In [41]:
print ("cross result========")
scores = cross_val_score(rf_clf, X_test, y_test, cv=3)
print (scores)
print (scores.mean())

cross result========
[1. 1. 1.]
1.0


In [42]:
# Load real test data
df_test = pd.read_csv('data/clean/Testing.csv')

In [43]:
X_acutal_test = df_test.iloc[:, :-1]
y_actual_test = df_test['prognosis']

In [30]:
print("Accuracy on acutal test: ", rf_clf.score(X_acutal_test, y_actual_test))

Accuracy on acutal test:  1.0


In [44]:
symptoms_dict = {}
for index, symptom in enumerate(X):
    symptoms_dict[symptom] = index

In [45]:
symptoms_dict

{'itching': 0,
 'skin_rash': 1,
 'nodal_skin_eruptions': 2,
 'continuous_sneezing': 3,
 'shivering': 4,
 'chills': 5,
 'joint_pain': 6,
 'stomach_pain': 7,
 'acidity': 8,
 'ulcers_on_tongue': 9,
 'muscle_wasting': 10,
 'vomiting': 11,
 'burning_micturition': 12,
 'spotting_ urination': 13,
 'fatigue': 14,
 'weight_gain': 15,
 'anxiety': 16,
 'cold_hands_and_feets': 17,
 'mood_swings': 18,
 'weight_loss': 19,
 'restlessness': 20,
 'lethargy': 21,
 'patches_in_throat': 22,
 'irregular_sugar_level': 23,
 'cough': 24,
 'high_fever': 25,
 'sunken_eyes': 26,
 'breathlessness': 27,
 'sweating': 28,
 'dehydration': 29,
 'indigestion': 30,
 'headache': 31,
 'yellowish_skin': 32,
 'dark_urine': 33,
 'nausea': 34,
 'loss_of_appetite': 35,
 'pain_behind_the_eyes': 36,
 'back_pain': 37,
 'constipation': 38,
 'abdominal_pain': 39,
 'diarrhoea': 40,
 'mild_fever': 41,
 'yellow_urine': 42,
 'yellowing_of_eyes': 43,
 'acute_liver_failure': 44,
 'fluid_overload': 45,
 'swelling_of_stomach': 46,
 'swelle

In [46]:
input_vector = np.zeros(len(symptoms_dict))
#input_vector

In [47]:
input_vector[[symptoms_dict['itching'], symptoms_dict['skin_rash']]] = 1
#input_vector

In [48]:
rf_clf.predict_proba([input_vector])

array([[0.  , 0.01, 0.05, 0.  , 0.  , 0.01, 0.  , 0.  , 0.01, 0.03, 0.  ,
        0.  , 0.  , 0.01, 0.16, 0.56, 0.01, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.06, 0.02, 0.  , 0.  , 0.01, 0.01,
        0.  , 0.  , 0.04, 0.  , 0.  , 0.  , 0.01, 0.  ]])

In [49]:
rf_clf.predict([input_vector])

array(['Fungal infection'], dtype=object)

# Hence it has 100% confidence to predict the disease. The prediction would improve once we take more symptoms as input.